spring:
  application:
    name: "api_produto"

resilience4j.circuitbreaker:
  instances:
    avaliacaoCB:
      minimumNumberOfCalls: 4
      slidingWindowSize: 8

management:
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: "api_produto"

# Configuration Tracing Jeager
opentracing:
  jaeger:
    service-name: "api_produto"
    sampler:
      type: "const"
      param: 1
    udp-sender:
      host: "localhost"
      port: "6831"