version: "3.3"

networks:
  aw-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config_prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data/prometheus
    networks:
      - aw-network
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      aw-network:

  jeager:
    image: jaegertracing/all-in-one:1.45
    container_name: jeager
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
