global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'monitoramento_api_produto_job'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    metrics_path: "actuator/prometheus"
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: "api_produto"