{
 "title": "api-produtos-observabilidade",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API  UPTIME",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "UPTIME",
     "type": "stat",
     "description": "API uptime",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "START TIME",
     "type": "stat",
     "description": "Hora da inicialização da API",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"} * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "API DB CONNECTION",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "JDBC POOL",
     "type": "stat",
     "description": "Pool de conexões JDBC",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections{application=\"$application\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "DB CONNECTION TIMEOUT",
     "type": "stat",
     "description": "Conexões com o database em timeout",
     "gridPos": { "h": 9, "w": 5, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(hikaricp_connections_timeout_total{application=\"$application\", instance=\"$instance\"}[5m])"
      }
     ]
    },
    {
     "title": "CONNECTION STATE",
     "type": "timeseries",
     "description": "Estado das conexões com o database",
     "gridPos": { "h": 9, "w": 15, "x": 9, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "active"
      },
      {
       "expr": "hikaricp_connections_idle{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "idle"
      },
      {
       "expr": "hikaricp_connections_pending{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "pending"
      }
     ]
    }
   ]
  },
  {
   "title": "API USE - MEMORY & CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "HEAP USED",
     "type": "gauge",
     "description": "Memória heap utilizada",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})* 100 / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "CPU UTILIZATION",
     "type": "timeseries",
     "description": "Utilização de CPU",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "System CPU usage"
      },
      {
       "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "Process CPU usage"
      }
     ]
    },
    {
     "title": "LOAD AVERAGE",
     "type": "timeseries",
     "description": "Média de uso de CPU",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_load_average_1m{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Load average"
      },
      {
       "expr": "system_cpu_count{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "CPU core size"
      }
     ]
    },
    {
     "title": "NON-HEAP USED",
     "type": "gauge",
     "description": "Memória non-heap utilizada ",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})* 100 / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "API RED - HTTP STATISTICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL REQUESTS",
     "type": "stat",
     "description": "Total de requisições no último minuto",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[5m]))"
      }
     ]
    },
    {
     "title": "ERROR FAMILY 500",
     "type": "stat",
     "description": "Número de erros da familia 500 nos últimos 5 minutos",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"5..\"}[5m]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "AVAILABILITY",
     "type": "timeseries",
     "description": "Disponibilidade dos últimos 5m",
     "gridPos": { "h": 11, "w": 16, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\", status!~\"5..\"}[5m])) / sum(rate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\"}[5m]))",
       "legendFormat": "availability 5m"
      }
     ]
    },
    {
     "title": "ERROR RATE",
     "type": "timeseries",
     "description": "Taxa de erros nos últimos 5 minutos",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"5..\", uri!=\"/actuator/prometheus\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[5m]))",
       "legendFormat": "5XX"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"4..\", uri!=\"/actuator/prometheus\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[5m]))",
       "legendFormat": "4XX"
      }
     ]
    },
    {
     "title": "RESPONSE TIME",
     "type": "timeseries",
     "description": "Tempo de resposta da API no último minuto",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\"}[5m]) / rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      }
     ]
    },
    {
     "title": "LATENCY AVERAGE",
     "type": "timeseries",
     "description": "Latência média por minuto",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[5m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[5m])) by (le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[5m])) by (le))",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[5m])) by (le))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.25, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[5m])) by (le))",
       "legendFormat": "25%"
      }
     ]
    },
    {
     "title": "MAX REQUEST DURATION",
     "type": "timeseries",
     "description": "Duração máxima de uma requisição",
     "gridPos": { "h": 17, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", status=\"200\", uri!=\"/actuator/prometheus\"}",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      }
     ]
    },
    {
     "title": "REQUEST COUNT",
     "type": "timeseries",
     "description": "Número de requisições por endpoint no último minuto",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[5m]))",
       "legendFormat": "/cursos"
      },
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[5m]))",
       "legendFormat": "/cursos/{id}"
      }
     ]
    },
    {
     "title": "AVERAGE REQUEST DURATION",
     "type": "timeseries",
     "description": "Duração média de requisições no último minuto",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status=\"200\"}[5m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=\"200\"}[5m])",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      },
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status=\"200\"}[5m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=\"200\"}[5m])",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      }
     ]
    }
   ]
  }
 ]
}